[target.aarch64-apple-darwin]
rustflags = ["-L", "/Applications/Postgres.app/Contents/Versions/latest/lib", "-l", "pq"]

[target.x86_64-apple-darwin]
rustflags = ["-L", "/Applications/Postgres.app/Contents/Versions/latest/lib", "-l", "pq"]
